# Generated by Django 6.0.5 on 2026-06-24 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_book_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='auto_returned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rental',
            name='renewal_count',
            field=models.IntegerField(default=0),
        ),
    ]
